export const YASHIE_ADMIN_COPY = {
  account: {
    description: "You can edit the website and choose what visitors can see.",
    signOut: "Sign out",
    signedIn: "Signed in",
    viewSite: "View site",
  },
  actions: {
    cancel: "Cancel",
    delete: "Delete",
    keep: "Keep it",
    newCategory: "New category",
    newGallery: "New gallery piece",
    newPost: "New post",
    newShop: "New shop item",
    newWorld: "New writing world",
    save: "Save",
    saving: "Saving",
  },
  dashboard: {
    eyebrow: "InkedByYashie",
    subtitle:
      "Edit the public site, organize its media, and move team work forward from one calm studio.",
    title: "Yashie Dashboard",
  },
  editor: {
    basics: "Basics",
    details: "Details",
    discardChanges: "Discard changes",
    image: "Image",
    imageHelp: "Choose a clear picture visitors will recognize.",
    keepEditing: "Keep editing",
    openPreview: "Open preview",
    publicView: "Visitor view",
    removed: "Removed.",
    saved: "Saved.",
    steps: {
      basics: {
        description: "Title, link, and visibility",
        label: "Basics",
      },
      danger: {
        description: "Remove this item",
        label: "Remove",
      },
      details: {
        description: "Category, timing, and summary",
        label: "Details",
      },
      image: {
        description: "Cover and image details",
        label: "Cover",
      },
      writing: {
        description: "Long-form body copy",
        label: "Writing",
      },
    },
    unsavedDescription:
      "You have changes that have not been saved yet. Keep editing or discard them before closing.",
    unsavedHeading: "Close without saving?",
    unsavedTitle: "Unsaved changes",
    visibility: "Visibility",
  },
  empty: {
    blog: "Start the first post from the editor.",
    categories:
      "Create labels first, then apply them to worlds, posts, and gallery pieces.",
    gallery: "Add the first gallery piece from the editor.",
    shop: "Add the first shop item from the editor.",
    worlds: "Add the first writing world from the editor.",
  },
  importSeed: {
    action: "Import website content",
    description:
      "The public site is showing built-in website content, but this dashboard has not imported it into the editor yet.",
    pending: "Importing...",
    success: "Website content imported.",
    title: "Bring the website content into this dashboard.",
  },
  errors: {
    delete: "We could not delete this item. Please try again.",
    importSeed: "We could not import the website content. Please try again.",
    save: "We could not save this item. Please try again.",
  },
  profile: {
    description:
      "Update your public details, page sections, website menu, and visitor links in one place.",
    heading: "Website details",
    linkRemoved: "Link removed. Save links to keep it.",
    links: "Links",
    menu: "Website menu",
    menuDescription:
      "Rename tabs or hide areas visitors should not open right now.",
    saved: "Saved.",
    showTab: "Show this tab",
    title: "Public profile",
  },
  members: {
    description:
      "See who can help edit this site. Manage invitations and access in Tuturuuu.",
    empty: "No team members were returned.",
    loading: "Loading team members...",
    manage: "Manage in Tuturuuu",
    title: "Team members",
    unavailable: "Team members are not available right now.",
  },
  publish: {
    check: "Review starter content",
    description:
      "Save once in the editor and visitors receive the update automatically. No extra publish step is required.",
    done: "All starter content is already present.",
    force: "Restore anyway",
    pending: "starter changes available",
    push: "Restore starter content",
    title: "Site status",
    warning:
      "Restoring would also replace or remove existing content. Review carefully before continuing.",
  },
  storage: {
    back: "Back",
    chooseFile: "Choose file",
    createFolder: "New folder",
    deleteDone: "Removed.",
    deleteHint:
      "This also clears it from any post, gallery piece, or shop item using it.",
    description:
      "See how much room your images, posts, and downloads are using.",
    driveDescription:
      "Open Tuturuuu Drive for deeper file management, sharing, and team folders.",
    driveLink: "Open Tuturuuu Drive",
    emptyFiles: "No files in this spot yet.",
    files: "Files",
    folderDone: "Folder added.",
    folderName: "Folder name",
    heading: "File room",
    largest: "Largest file",
    limit: "Plan limit",
    noFiles: "No files have been added yet.",
    of: "of",
    open: "Open",
    refresh: "Refresh",
    remove: "Remove",
    rename: "Rename",
    renameDone: "Renamed.",
    root: "Main room",
    upload: "Upload",
    uploadDone: "Uploaded.",
    uploadHelp: "Choose the same name to replace an existing file.",
    smallest: "Smallest file",
    title: "Storage",
    unavailableTitle: "Storage details are unavailable",
    unknownDate: "Date unavailable",
    used: "Used",
  },
  tabs: {
    account: "Account",
    blog: "Blog",
    categories: "Categories",
    gallery: "Gallery",
    members: "Members",
    publish: "Site status",
    profile: "Profile & Links",
    shop: "Shop",
    storage: "Storage",
    tasks: "Tasks",
    worlds: "Worlds",
  },
  visibility: {
    archived: "Hidden",
    draft: "Draft",
    published: "Live",
    scheduled: "Scheduled",
  },
} as const;
